# site.theme: [default|card]
site:
    theme: default
    store:
      root: /data/mblog/
      size: 2
spring:
    datasource:
        #schema: classpath*:config/db/db_mblog.sql
        #initialization-mode: always
        #continue-on-error: false
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://116.62.143.100/db_mblog?useSSL=false&characterEncoding=utf8
        username: root
        password: 123456
    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.config.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.store.root}/indexes
aliyun:
  oss:
    config:
      enabled: true
      bucketName: mblog666
      endpoint: oss-cn-hangzhou.aliyuncs.com
      accessKeyId: LTAIkwOP3oxABoOp
      secretAccessKey: Wl0RJIikmE5l34WBDekPq5Bsfdbcxb
      remoteEndpoint: mblog666.oss-cn-hangzhou.aliyuncs.com